POST http://localhost:3000/user/signup
Content-Type: application/json

{
"name": "teste4", 
"email": "email4@email.com", 
"password": "1234567",
"role": "ADMIN"
}

####

GET  http://localhost:3000/user/login
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFlNDE3YzIzLWE2ZDUtNGJmMy1hMTdiLWMwYzc0MDdhNWJlYyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTA4OTAzMywiZXhwIjoxNjc5MDk2MjMzfQ.yoF1VPEK82ZRnpTHCSH5A0J8hDGRncv7rGsJke3mADo

{
"email": "email4@email.com", 
"password": "1234567"
}

###
GET  http://localhost:3000/user/login/1e417c23-a6d5-4bf3-a17b-c0c7407a5bec
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFlNDE3YzIzLWE2ZDUtNGJmMy1hMTdiLWMwYzc0MDdhNWJlYyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTA4OTAzMywiZXhwIjoxNjc5MDk2MjMzfQ.yoF1VPEK82ZRnpTHCSH5A0J8hDGRncv7rGsJke3mADo

{
"email": "email4@email.com", 
"password": "1234567"
}
